<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Java Streams' Course: Introduction to Java Streams</description>
    <name>introduction-to-java-streams</name>

    <groupId>com.baeldung</groupId>
    <artifactId>ljs-introduction-to-java-streams</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>creating-streams-start</module>
        <module>creating-streams-end</module>
        <module>intermediate-and-terminal-operations-start</module>
        <module>intermediate-and-terminal-operations-end</module>
    </modules>
</project>
