package springsecurity.lesson2multipleprovidersandauthenticationmanager.persistance.repository;


import org.springframework.data.jpa.repository.JpaRepository;
import springsecurity.lesson2multipleprovidersandauthenticationmanager.persistance.model.SecurityQuestionDefinition;

public interface SecurityQuestionDefinitionRepository extends JpaRepository<SecurityQuestionDefinition, Long> {

}