<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Java Collections' Course: Deep Dive Into Lists</description>
    <name>deep-dive-into-lists</name>

    <groupId>com.baeldung</groupId>
    <artifactId>ljc-deep-dive-into-lists</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>introduction-arraylists-start</module>
        <module>introduction-arraylists-end</module>
        <module>basic-arraylist-operations-start</module>
        <module>basic-arraylist-operations-end</module>
        <module>bulk-operations-on-lists-start</module>
        <module>bulk-operations-on-lists-end</module>
        <module>introduction-linkedlists-start</module>
        <module>introduction-linkedlists-end</module>
    </modules>
</project>
