<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Java Streams' Course: Introduction to Functional Programming</description>
    <name>introduction-to-functional-programming</name>

    <groupId>com.baeldung</groupId>
    <artifactId>ljs-introduction-to-functional-programming</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>functional-programming-and-java-streams-start</module>
        <module>functional-programming-and-java-streams-end</module>
        <module>functional-interfaces-and-lambdas-in-java-start</module>
        <module>functional-interfaces-and-lambdas-in-java-end</module>
    </modules>
</project>
