package springsecurity.lesson3springsecuritycustomexpressions.persistance.repository;


import org.springframework.data.jpa.repository.JpaRepository;
import springsecurity.lesson3springsecuritycustomexpressions.persistance.model.SecurityQuestionDefinition;

public interface SecurityQuestionDefinitionRepository extends JpaRepository<SecurityQuestionDefinition, Long> {

}